/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 01-May-2017 15:12:58
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 200
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
int bandpassMorseLen = 200;
short bandpassMorse[200] = {
       35,     46,     57,     68,     80,     92,    104,    115,    126,
      136,    145,    153,    159,    164,    167,    167,    166,    163,
      157,    150,    140,    129,    117,    103,     89,     74,     59,
       44,     29,     16,      4,     -6,    -14,    -20,    -24,    -25,
      -24,    -20,    -14,     -5,      5,     17,     29,     43,     56,
       69,     80,     89,     96,    100,    100,     96,     87,     73,
       53,     28,     -2,    -37,    -77,   -122,   -171,   -223,   -278,
     -334,   -390,   -446,   -500,   -551,   -598,   -639,   -674,   -701,
     -720,   -729,   -728,   -716,   -692,   -658,   -612,   -556,   -488,
     -411,   -325,   -231,   -130,    -24,     86,    197,    310,    421,
      528,    631,    728,    816,    894,    962,   1018,   1060,   1089,
     1103,   1103,   1089,   1060,   1018,    962,    894,    816,    728,
      631,    528,    421,    310,    197,     86,    -24,   -130,   -231,
     -325,   -411,   -488,   -556,   -612,   -658,   -692,   -716,   -728,
     -729,   -720,   -701,   -674,   -639,   -598,   -551,   -500,   -446,
     -390,   -334,   -278,   -223,   -171,   -122,    -77,    -37,     -2,
       28,     53,     73,     87,     96,    100,    100,     96,     89,
       80,     69,     56,     43,     29,     17,      5,     -5,    -14,
      -20,    -24,    -25,    -24,    -20,    -14,     -6,      4,     16,
       29,     44,     59,     74,     89,    103,    117,    129,    140,
      150,    157,    163,    166,    167,    167,    164,    159,    153,
      145,    136,    126,    115,    104,     92,     80,     68,     57,
       46,     35
};
