/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 01-May-2017 15:14:37
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 200
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */


/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
int bandpassSSBLen = 200;
short bandpassSSB[200] = {
       45,     49,     44,     29,      6,    -21,    -49,    -75,    -93,
     -102,   -100,    -87,    -65,    -38,    -11,     12,     26,     28,
       16,     -8,    -42,    -82,   -122,   -156,   -180,   -188,   -181,
     -158,   -125,    -85,    -46,    -15,      2,      1,    -19,    -57,
     -108,   -165,   -220,   -265,   -292,   -298,   -281,   -243,   -190,
     -130,    -74,    -32,    -11,    -17,    -50,   -109,   -184,   -267,
     -344,   -403,   -435,   -433,   -398,   -332,   -245,   -151,    -66,
       -3,     25,     10,    -49,   -145,   -266,   -396,   -514,   -601,
     -641,   -625,   -550,   -425,   -265,    -94,     62,    176,    224,
      191,     73,   -123,   -375,   -650,   -910,  -1109,  -1207,  -1169,
     -974,   -617,   -109,    518,   1219,   1938,   2612,   3182,   3594,
     3810,   3810,   3594,   3182,   2612,   1938,   1219,    518,   -109,
     -617,   -974,  -1169,  -1207,  -1109,   -910,   -650,   -375,   -123,
       73,    191,    224,    176,     62,    -94,   -265,   -425,   -550,
     -625,   -641,   -601,   -514,   -396,   -266,   -145,    -49,     10,
       25,     -3,    -66,   -151,   -245,   -332,   -398,   -433,   -435,
     -403,   -344,   -267,   -184,   -109,    -50,    -17,    -11,    -32,
      -74,   -130,   -190,   -243,   -281,   -298,   -292,   -265,   -220,
     -165,   -108,    -57,    -19,      1,      2,    -15,    -46,    -85,
     -125,   -158,   -181,   -188,   -180,   -156,   -122,    -82,    -42,
       -8,     16,     28,     26,     12,    -11,    -38,    -65,    -87,
     -100,   -102,    -93,    -75,    -49,    -21,      6,     29,     44,
       49,     45
};
