/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 14-May-2017 15:24:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 200
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint16 filter coefficients.
 */
int bandpassMorseLen = 200;
short bandpassMorse[200] = {
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      1,      6,     12,     19,     27,     35,
       44,     54,     64,     75,     86,     97,    108,    119,    129,
      139,    147,    155,    160,    164,    166,    166,    163,    158,
      150,    138,    124,    107,     86,     63,     36,      7,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,     17,     86,    156,    225,    293,    359,
      422,    481,    536,    586,    630,    668,    699,    722,    738,
      746,    746,    738,    722,    699,    668,    630,    586,    536,
      481,    422,    359,    293,    225,    156,     86,     17,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      7,     36,     63,     86,    107,    124,
      138,    150,    158,    163,    166,    166,    164,    160,    155,
      147,    139,    129,    119,    108,     97,     86,     75,     64,
       54,     44,     35,     27,     19,     12,      6,      1,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0,      0,      0,      0,      0,      0,      0,      0,
        0,      0
};
